### ISSUE TITLE
Problema ao adicionar Item com o Selenium

### ISSUE THREAD

**Issue by danielolinto31** [andersonolisilva/lojapedido#1]
Consegui fazer com o método "deveAdicionarUmItem()" funcionasse. Porém, por algum motivo, ele está inserindo um zero (0) a mais no valor do produto, ou seja, peço para cadastrar um iPhone de R$ 2.800,00, mas na listagem vai R$ 28.000,00.

Eu acredito que deva ser porque na classe de domínio esteja sendo utilizado o BigDecimal e nas de teste esteja sendo usado o Double.

Segue anexo o print da tela. Veja se você já pegou algum erro parecido.

![image](https://cloud.githubusercontent.com/assets/7100332/11648239/b1cdd3d2-9d50-11e5-9a35-1865f73292d0.png)

**Comment by danielolinto31** [comment]
Dei uma estudada no BigDecimal e vi aquele ele usa String. Ao invés de trabalhar com Double nos testes, coloquei todos Strings e deu certo. Só alegria!

![image](https://cloud.githubusercontent.com/assets/7100332/11649072/98977ea0-9d59-11e5-8f57-793c9af63ead.png)

**Comment by andersonolisilva** [comment]
Vi as imagens acima, mas quando fui rodar todos os testes apresentaram erros e falhas em outros testes como mostra na imagem.
![image](https://cloud.githubusercontent.com/assets/2801535/11654305/5394cc2a-9d83-11e5-8caf-cdfe2c594064.png)

**Comment by andersonolisilva** [comment]
Problema  corrigido, alterando a forma de execução do botão, utilizando o javascript ao invés do .click nativo do selenium.
